name: dotnet1

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  TEST_PROJ: 'src/PromoCodeTests'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
      
    - name: Install dependencies, build and test
      working-directory: ${{ env.TEST_PROJ }}
      run: |
        dotnet restore
        dotnet build
        dotnet test
